"""add model architecture

Revision ID: 18b876610434
Revises: c9652d186657
Create Date: 2026-07-16 23:06:31.298001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18b876610434'
down_revision: Union[str, Sequence[str], None] = 'c9652d186657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_runs', sa.Column('hidden_dim', sa.Integer(), nullable=False))
    op.add_column('training_runs', sa.Column('output_dim', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_runs', 'output_dim')
    op.drop_column('training_runs', 'hidden_dim')
    # ### end Alembic commands ###
