"""create training runs table

Revision ID: 329ee8e8f9fa
Revises: a6b5f9088d01
Create Date: 2026-07-16 16:51:14.164326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '329ee8e8f9fa'
down_revision: Union[str, Sequence[str], None] = 'a6b5f9088d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('graph_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('epochs', sa.Integer(), nullable=False),
    sa.Column('learning_rate', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('loss', sa.Float(), nullable=False),
    sa.Column('checkpoint', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['graph_id'], ['graphs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_runs')
    # ### end Alembic commands ###
