"""add simulation tables

Revision ID: 530aab7ae9ae
Revises: 881a442014bf
Create Date: 2026-07-22 21:53:18.552553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '530aab7ae9ae'
down_revision: Union[str, Sequence[str], None] = '881a442014bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('graph_id', sa.UUID(), nullable=False),
    sa.Column('training_run_id', sa.UUID(), nullable=True),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('gamma', sa.Float(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['graph_id'], ['graphs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_run_id'], ['training_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('simulation_run_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('susceptible', sa.Integer(), nullable=False),
    sa.Column('infected', sa.Integer(), nullable=False),
    sa.Column('recovered', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_steps')
    op.drop_table('simulation_runs')
    # ### end Alembic commands ###
