"""add graph html

Revision ID: a6b5f9088d01
Revises: 838c96c281be
Create Date: 2026-07-16 16:21:22.884157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b5f9088d01'
down_revision: Union[str, Sequence[str], None] = '838c96c281be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graphs', sa.Column('html_file', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('graphs', 'html_file')
    # ### end Alembic commands ###
