"""add training metrics

Revision ID: c9652d186657
Revises: 329ee8e8f9fa
Create Date: 2026-07-16 21:45:27.920692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9652d186657'
down_revision: Union[str, Sequence[str], None] = '329ee8e8f9fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_runs', sa.Column('precision', sa.Float(), nullable=False))
    op.add_column('training_runs', sa.Column('recall', sa.Float(), nullable=False))
    op.add_column('training_runs', sa.Column('f1', sa.Float(), nullable=False))
    op.add_column('training_runs', sa.Column('training_time', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_runs', 'training_time')
    op.drop_column('training_runs', 'f1')
    op.drop_column('training_runs', 'recall')
    op.drop_column('training_runs', 'precision')
    # ### end Alembic commands ###
