"""add training_run metrics fields

Revision ID: d926b465677a
Revises: 18b876610434
Create Date: 2026-07-18 16:07:36.375607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd926b465677a'
down_revision: Union[str, Sequence[str], None] = '18b876610434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_runs', sa.Column('history', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_runs', 'history')
    # ### end Alembic commands ###
